### Preprocessing Data CNBC

In [3]:
import pandas as pd
import re
CNBC_DATA_PATH = '../../data/data_berita/cleaning/cnbc'

In [18]:
df_cleaned = pd.read_csv(f'{CNBC_DATA_PATH}/cnbc_cleaned_full.csv')

In [19]:
display(df_cleaned.head())
display(df_cleaned.tail())

,date,title,content,content_length
0,2019-09-01,"Kondusif, Menkominfo Siap Buka Kembali Interne...","Jakarta, CNBC Indonesia -Menteri Koordinator B...",2063
1,2019-09-02,Wiranto Pastikan Papua Mulai Kondusif,"Jakarta, CNBC Indonesia-Pasca aksi demonstrasi...",795
2,2019-09-03,"Brexit Berlarut-larut, Boris Johnson Ancam Par...","Jakarta, CNBC Indonesia- Perdana Menteri Inggr...",4047
3,2019-09-04,"Salip RI, di Vietnam Tanah Gratis, Buruhnya Pr...","Jakarta, CNBC Indonesia -Bank Dunia melaporkan...",2274
4,2019-09-04,Pemimpin Hong Kong Resmi Cabut RUU Ekstradisi,"Jakarta, CNBC Indonesia -Kepala Eksekutif Hong...",453

,date,title,content,content_length
5055,2024-09-30,"Aksi Israel Bunuh Nasrallah Guncang Dunia, Pau...","Jakarta, CNBC Indonesia- Kematian pemimpin Hiz...",2286
5056,2024-09-30,Awas Perang Baru Israel! Setelah Bunuh Nasrall...,"Jakarta, CNBC Indonesia-Timur Tengah semakin p...",2853
5057,2024-09-30,"Perang Arab Makin Kacau, AS Sinyal Terjunkan P...","Jakarta, CNBC Indonesia-Amerika Serikat (AS)ke...",3129
5058,2024-09-30,"6 Update Perang Arab: Invasi Darat Israel, Ira...","Jakarta, CNBC Indonesia- Perang Israel di wila...",5910
5059,2024-09-30,"9 Update Perang Arab: Israel Bom Yaman, Iran N...","Jakarta, CNBC Indonesia- Perang di wilayah Ara...",8248

In [20]:
df = pd.read_csv(
    f"{CNBC_DATA_PATH}/cnbc_labeled_manual_raw.csv",
    sep="\t",
    encoding="latin1",
    engine="python"
)

df.head()

,id,date,title,text_preview,sentiment,confidence,notes,content,content_length,article_id
0,1,9/11/2019,Menko Luhut : Jokowi Tak Mungkin Asal Pilih Me...,"Jakarta, CNBC Indonesia- Presiden Joko Widodo ...",neutral,NaN,NaN,"Jakarta, CNBC Indonesia- Presiden Joko Widodo ...",2400,CNBC_00008
1,2,9/24/2019,Ini Siasat Lobi-Lobi Boris Saat Brexit Makin U...,"Jakarta, CNBC Indonesia-Kurang dari 40 hari je...",neutral,NaN,NaN,"Jakarta, CNBC Indonesia-Kurang dari 40 hari je...",216,CNBC_00012
2,3,10/6/2019,"Menterinya Terbanyak Se-ASEAN, Kabinet RI Baka...","CNBC Indonesia, Jakarta -Jelang pelantikan Kab...",neutral,NaN,NaN,"CNBC Indonesia, Jakarta -Jelang pelantikan Kab...",2504,CNBC_00017
3,4,10/16/2019,Akankah Gerindra Masuk Koalisi Jokowi?,"Jakarta, CNBC Indonesia -Partai Gerindra mengg...",neutral,NaN,NaN,"Jakarta, CNBC Indonesia -Partai Gerindra mengg...",642,CNBC_00023
4,5,10/16/2019,"Kubu Prabowo Masuk Koalisi Jokowi, Berkah atau...","Berbicara mengenai perekonomian, investasi men...",positive,NaN,NaN,"Berbicara mengenai perekonomian, investasi men...",7186,CNBC_00026

In [21]:
df.columns

Index(['id', 'date', 'title', 'text_preview', 'sentiment', 'confidence',
       'notes', 'content', 'content_length', 'article_id'],
      dtype='object')

In [27]:
# regex + clean function
URL_RE = re.compile(r"(https?://\S+|www\.\S+)", flags=re.IGNORECASE)
HTML_RE = re.compile(r"<[^>]+>")
WS_RE = re.compile(r"\s+")
SYMBOL_RE = re.compile(r"[^a-zA-Z0-9\s\.,!?\'\-]")

def clean_text(s: str) -> str:
    if pd.isna(s):
        return ""
    s = str(s)
    s = HTML_RE.sub(" ", s)
    s = URL_RE.sub(" ", s)
    s = SYMBOL_RE.sub(" ", s)
    s = s.lower()
    s = WS_RE.sub(" ", s).strip()
    return s

#cleaning title & content
df['content'] = (
    df['content']
    .astype(str)
    .str.replace(r'^\s*.*?CNBC\s+Indonesia.*?-\s*', '', regex=True)
    .str.strip()
)



df["title_clean"] = df["title"].apply(clean_text)
df["content_clean"] = df["content"].apply(clean_text)

In [28]:
df.head()

,id,date,title,text_preview,sentiment,confidence,notes,content,content_length,article_id,title_clean,content_clean
0,1,9/11/2019,Menko Luhut : Jokowi Tak Mungkin Asal Pilih Me...,"Jakarta, CNBC Indonesia- Presiden Joko Widodo ...",neutral,NaN,NaN,Presiden Joko Widodo (Jokowi) menegaskan susua...,2400,CNBC_00008,menko luhut jokowi tak mungkin asal pilih ment...,presiden joko widodo jokowi menegaskan susuan ...
1,2,9/24/2019,Ini Siasat Lobi-Lobi Boris Saat Brexit Makin U...,"Jakarta, CNBC Indonesia-Kurang dari 40 hari je...",neutral,NaN,NaN,Kurang dari 40 hari jelang tenggat waktu Inggr...,216,CNBC_00012,ini siasat lobi-lobi boris saat brexit makin u...,kurang dari 40 hari jelang tenggat waktu inggr...
2,3,10/6/2019,"Menterinya Terbanyak Se-ASEAN, Kabinet RI Baka...","CNBC Indonesia, Jakarta -Jelang pelantikan Kab...",neutral,NaN,NaN,"negara tetangga kita, di Asia Tenggara. Berdas...",2504,CNBC_00017,"menterinya terbanyak se-asean, kabinet ri baka...","negara tetangga kita, di asia tenggara. berdas..."
3,4,10/16/2019,Akankah Gerindra Masuk Koalisi Jokowi?,"Jakarta, CNBC Indonesia -Partai Gerindra mengg...",neutral,NaN,NaN,Partai Gerindra menggelar rapat kerja nasional...,642,CNBC_00023,akankah gerindra masuk koalisi jokowi?,partai gerindra menggelar rapat kerja nasional...
4,5,10/16/2019,"Kubu Prabowo Masuk Koalisi Jokowi, Berkah atau...","Berbicara mengenai perekonomian, investasi men...",positive,NaN,NaN,orang yang memang sangat kredibel seperti Sri ...,7186,CNBC_00026,"kubu prabowo masuk koalisi jokowi, berkah atau...",orang yang memang sangat kredibel seperti sri ...

In [29]:
#collect needed data
df_final = df[
    ["date", "title_clean", "content_clean", "sentiment", "article_id"]
].copy()

df_final = df_final.rename(
    columns={
        "title_clean": "title",
        "content_clean": "content"
    }
)

# gabungin buat input IndoBERT
df_final["text"] = (
    df_final["title"].str.strip() + ". " +
    df_final["content"].str.strip()
).str.strip()

df_final.head()

,date,title,content,sentiment,article_id,text
0,9/11/2019,menko luhut jokowi tak mungkin asal pilih ment...,presiden joko widodo jokowi menegaskan susuan ...,neutral,CNBC_00008,menko luhut jokowi tak mungkin asal pilih ment...
1,9/24/2019,ini siasat lobi-lobi boris saat brexit makin u...,kurang dari 40 hari jelang tenggat waktu inggr...,neutral,CNBC_00012,ini siasat lobi-lobi boris saat brexit makin u...
2,10/6/2019,"menterinya terbanyak se-asean, kabinet ri baka...","negara tetangga kita, di asia tenggara. berdas...",neutral,CNBC_00017,"menterinya terbanyak se-asean, kabinet ri baka..."
3,10/16/2019,akankah gerindra masuk koalisi jokowi?,partai gerindra menggelar rapat kerja nasional...,neutral,CNBC_00023,akankah gerindra masuk koalisi jokowi?. partai...
4,10/16/2019,"kubu prabowo masuk koalisi jokowi, berkah atau...",orang yang memang sangat kredibel seperti sri ...,positive,CNBC_00026,"kubu prabowo masuk koalisi jokowi, berkah atau..."

In [30]:
#normalized label
sentiment_map = {
    "positive": 1,
    "neutral": 0,
    "negative": -1
}

df_final["sentiment"] = df_final["sentiment"].str.lower().str.strip()
df_final["label"] = df_final["sentiment"].map(sentiment_map)

#bikin date jdi datetime
df_final["date"] = pd.to_datetime(
    df_final["date"],
    format="%m/%d/%Y",
    errors="coerce"
)


# buang sentiment string
df_final = df_final.drop(columns=["sentiment"])

In [31]:
df_final.head()

,date,title,content,article_id,text,label
0,2019-09-11,menko luhut jokowi tak mungkin asal pilih ment...,presiden joko widodo jokowi menegaskan susuan ...,CNBC_00008,menko luhut jokowi tak mungkin asal pilih ment...,0
1,2019-09-24,ini siasat lobi-lobi boris saat brexit makin u...,kurang dari 40 hari jelang tenggat waktu inggr...,CNBC_00012,ini siasat lobi-lobi boris saat brexit makin u...,0
2,2019-10-06,"menterinya terbanyak se-asean, kabinet ri baka...","negara tetangga kita, di asia tenggara. berdas...",CNBC_00017,"menterinya terbanyak se-asean, kabinet ri baka...",0
3,2019-10-16,akankah gerindra masuk koalisi jokowi?,partai gerindra menggelar rapat kerja nasional...,CNBC_00023,akankah gerindra masuk koalisi jokowi?. partai...,0
4,2019-10-16,"kubu prabowo masuk koalisi jokowi, berkah atau...",orang yang memang sangat kredibel seperti sri ...,CNBC_00026,"kubu prabowo masuk koalisi jokowi, berkah atau...",1

In [32]:
df_final["date"].head()
df_final["date"].isna().sum()

np.int64(0)

In [33]:
df_final["label"].value_counts(dropna=False)

label
 0    561
 1    126
-1    112
Name: count, dtype: int64

In [35]:
# jadiin csv
df_final.to_csv(
    f"{CNBC_DATA_PATH}/cnbc_cleaned_labeled_manual.csv",
    index=False,
    encoding="utf-8"
)