In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import csv
import time
import requests
from bs4 import BeautifulSoup
import re
import os
from urllib.parse import urlparse, parse_qs
import time


from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options

headers = {
    'User-Agent' : 'Mozilla/5.0 (Windows NT 10.0; Win 64; x64) AppleWebKit/537.36 (KHTML, Like Gecko) Chrome/140.0.0.0 Safari/537.36 Edg/140.0.0.0'
}

In [12]:
#setup for csv (write)
CSV_HEADERS = ['title', 'tanggal', 'waktu', 'content']

#function to save to csv
def write_data_to_csv(filename, headers, data):
    try:
        with open(filename, 'w', newline='', encoding='utf-8') as f:
            writer = csv.writer(f)
            writer.writerow(headers) #  header
            writer.writerows(data)  #  data
        print(f"\n✅ SUCCESS: Total {len(data)} articles successfully saved to '{filename}'")
    except Exception as e:
        print(f"\n❌ FATAL ERROR: Failed to write data to CSV file '{filename}'. Error: {e}")

In [23]:
#setup for csv (append)
def append_rows_to_csv(filename, headers, rows):
    """
    Append baris ke CSV. Header hanya ditulis jika file belum ada atau header belum ada.
    Force flush+fsync di dalam blok 'with' supaya tidak ada operasi setelah file ditutup.
    """
    try:
        # Normalisasi rows (kalau generator/iterator, materialize biar aman)
        rows_to_write = list(rows)
        if not rows_to_write:
            print("Tidak ada baris untuk ditulis.")
            return

        write_header = True
        if os.path.exists(filename):
            # Cek apakah header sudah ada
            try:
                with open(filename, 'r', newline='', encoding='utf-8') as rf:
                    reader = csv.reader(rf)
                    first = next(reader, None)
                    write_header = (first != headers)
            except Exception:
                # Kalau gagal baca (file kosong/korup), kita tulis header lagi saja
                write_header = True

        # Tulis append
        with open(filename, 'a', newline='', encoding='utf-8') as f:
            w = csv.writer(f)
            if write_header:
                w.writerow(headers)
            w.writerows(rows_to_write)

            # Pastikan buffer flush sebelum keluar dari 'with'
            f.flush()
            try:
                os.fsync(f.fileno())
            except Exception:
                # fsync bisa gagal di beberapa FS; aman diabaikan
                pass

        print(f"💾 APPEND: {len(rows_to_write)} baris disimpan ke '{filename}'")

    except Exception as e:
        print(f"❌ ERROR APPEND CSV '{filename}': {e}")

# OKEZONE

In [4]:
urlokezone = 'https://search.okezone.com/search?q=politik&highlight=1&sort=desc&start=0'
resokezone = requests.get(urlokezone, headers=headers)

soupokezone = BeautifulSoup(resokezone.text, 'lxml')
# print(soupokezone)

In [5]:
def checklastpage(url):
    lastpage = -1
    # Setup Chrome
    chrome_options = Options()
    chrome_options.add_argument("--headless")  # jalan background
    chrome_options.add_argument("--no-sandbox")
    chrome_options.add_argument("--disable-dev-shm-usage")


    driver = webdriver.Chrome(options=chrome_options)

    try:
        driver.get(url)
        
        wait = WebDriverWait(driver, 10)
        
        try:
            pagination_elements = wait.until(EC.presence_of_all_elements_located((By.TAG_NAME, "a")))
            
            loaddata_links = []
            for element in pagination_elements:
                href = element.get_attribute('href')
                if href and 'loaddata' in href:
                    loaddata_links.append({
                        'href': href,
                        'text': element.text.strip()
                    })
            
            print(f"Found {len(loaddata_links)} loaddata links:")
            for link in loaddata_links:
                print(f"Link: {link['href']} - Text: '{link['text']}'")
            
            last_links = [link for link in loaddata_links if link['text'].lower() == 'last']
            
            if last_links:
                last_link = last_links[0]
                href = last_link['href']
                print(f"\nFound Last link: {href}")
                
                match = re.search(r'/(\d+)/?$', href)
                if match:
                    lastpage = int(match.group(1))
                    print(f"Last page number: {lastpage}")
                else:
                    print("Could not extract page number")
            else:
                print("No Last link found")
                
        except Exception as e:
            print(f"Error waiting on pagination: {e}")
            
            page_source = driver.page_source
            soup_selenium = BeautifulSoup(page_source, 'lxml')
            
            loaddata_links = soup_selenium.find_all('a', href=lambda x: x and 'loaddata' in x)
            print(f"\nFrom page source - Found {len(loaddata_links)} loaddata links:")
            
            for link in loaddata_links[:5]:
                print(f"Link: {link.get('href')} - Text: '{link.get_text().strip()}'")

    finally:
        driver.quit()
    return lastpage

In [6]:
totalpage = checklastpage(urlokezone)

Found 0 loaddata links:
No Last link found

In [7]:
print(f"page yg bisa di scrap: {totalpage}")

page yg bisa di scrap: -1

In [ ]:
# baca link berita
def getarticle_okezone(link):
  try:
    res = requests.get(link, headers=headers)
    soup = BeautifulSoup(res.text, 'lxml')
    div_content = soup.find('div', class_='c-detail read') #ganti class sesuai nama class di artikel
    paragraphs = div_content.find_all('p') #ganti tiap tag paragraf
    content = ' '.join([p.get_text(strip=True) for p in paragraphs])
    return content
    
  except Exception as e:
    print(f"Error baca artikel di: {link} | {e}")
  return ''

In [ ]:
#SCRAPING
okezone = []
counter = 0

#MAIN FUNCTION - okezone
for page in range(1, totalpage+1):
    print(f'\n--- Scraping page: {page} ---')
    url = f'https://search.okezone.com/loaddata/article/politik/{page}'
    try:
        res = requests.get(url, headers=headers)

        soup = BeautifulSoup(res.text, 'lxml')
        articles = soup.find_all('div', class_='subgroup')

        if not articles:
             print(f"No articles found on page {page}. Stopping.")
             break

        for art in articles:
            desc = art.select_one('div', class_='desc_section')
            try:
                title = desc.select_one('a').text.strip()
                link = desc.select_one('a', class_='desc-text')['href']

                #ambil tanggal
                temp = desc.find('a', class_='time-text')
                tanggal_waktu = temp.text.strip()
                tanggal = tanggal_waktu.split(' ')[0] + ' ' + tanggal_waktu.split(' ')[1] + ' ' + tanggal_waktu.split(' ')[2] #tanggalnya
                waktu = tanggal_waktu.split(' ')[3] + ' ' + tanggal_waktu.split(' ')[4] #jamnya


                content = getarticle_okezone(link)

                # Simpan data ke list
                okezone.append([title, tanggal, waktu, content])
                
                print(f'✅ Article #{counter+1} SCRAPPED! Title: {title[:50]}...')
                print(f'    100 KARAKTER PERTAMA DI CONTENT: {content[:100]} \n Waktu: {tanggal}')
                counter += 1
                time.sleep(1)
            except Exception as e:
                print(f"Error parsing artikel on page: {page} | {e}")
                continue
    except Exception as e:
        print(f"Error scraping on page: {page} | {e}")
        continue

--- Scraping page: 1 ---
✅ Article #1 SCRAPPED! Title: Pak Bas Lapor Progres IKN ke Istana, Persiapan Ibu...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Kepala Otorita Ibu Kota Nusantara (OIKN) Basuki Hadimuljono merapat ke Kementerian Sekretar
 Waktu: 03 Oktober 2025
✅ Article #2 SCRAPPED! Title: Fenomena Selebriti di Politik, Begini Pandangan Su...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Dalam episode terbaru Bisikan Gaib, Robby Purba menghadirkan tamu spesial, Ki Atmo, yang di
 Waktu: 01 Oktober 2025
✅ Article #3 SCRAPPED! Title: SAS Institute: Program MBG Bukan Janji Politik, Ta...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA– Badan Gizi Nasional (BGN) mencatat hingga 22 September 2025, terdapat 4.711 kasus bakteri
 Waktu: 01 Oktober 2025
✅ Article #4 SCRAPPED! Title: Husnan Bey: PPP Harus Kembali ke Khitah, Jangan Ja...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Muktamar X Partai Persatuan Pembangunan (PPP) yang baru saja berakhir memunculkan dualisme
 Waktu: 30 September 2025
✅ Article #5 SCRAPPED! Title: Jokowi Sambut Baik Keputusan Prabowo Soal IKN Jadi...
    100 KARAKTER PERTAMA DI CONTENT:  SOLO– Keputusan Presiden Prabowo Subianto menetapkan Ibu Kota Nusantara (IKN), sebagai pusat politi
 Waktu: 26 September 2025
✅ Article #6 SCRAPPED! Title: IKN Ditetapkan sebagai Ibu Kota Politik 2028, Pram...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA– Presiden Prabowo Subianto telah menetapkan Ibu Kota Nusantara (IKN), sebagai Ibu Kota Poli
 Waktu: 24 September 2025
✅ Article #7 SCRAPPED! Title: Menerka Rencana Politik Jokowi di Balik Instruksi ...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Analis komunikasi politik Hendri Satrio menganalisis instruksi Presiden ke-7 RI, Joko Widod
 Waktu: 23 September 2025
✅ Article #8 SCRAPPED! Title: Breaking News! Prabowo Tetapkan IKN Ibu Kota Polit...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA -PresidenPrabowo Subiantomenegaskan, pembangunan Ibu Kota Nusantara (IKN) tetap berlanjut. M
 Waktu: 19 September 2025
✅ Article #9 SCRAPPED! Title: Jejak Darah Politik Amerika, Pembunuhan Lincoln hi...
    100 KARAKTER PERTAMA DI CONTENT: AMERIKA SERIKATmemiliki sejarah politik yang cukup panjang. Sistem demokrasi yang masuk kategori bai
 Waktu: 15 September 2025
✅ Article #10 SCRAPPED! Title: RUU Perampasan Aset Disorot, Pakar Hukum: Waspadai...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA– Dewan Perwakilan Rakyat (DPR) resmi mengambil alih inisiatif Rancangan Undang-Undang (RUU)
 Waktu: 11 September 2025

--- Scraping page: 2 ---
✅ Article #11 SCRAPPED! Title: Prabowo: Perdagangan dan Keuangan Kini Jadi Senjat...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Presiden Prabowo Subianto menyoroti bahwa saat ini perdagangan dan keuangan global dimainka
 Waktu: 09 September 2025
✅ Article #12 SCRAPPED! Title: Perdana Menteri Francois Bayrou Dilengserkan, Perp...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– ParlemenPrancisresmi melengserkan Perdana Menteri Francois Bayrou beserta pemerintahannya a
 Waktu: 09 September 2025
✅ Article #13 SCRAPPED! Title: Krisis Politik Thailand Imbas Rekaman Telepon Boco...
    100 KARAKTER PERTAMA DI CONTENT: BANGKOK- Krisis politik tengah melandaThailanddalam beberapa hari terakhir setelah rekaman telepon P
 Waktu: 05 September 2025
✅ Article #14 SCRAPPED! Title: Partai Perindo Respons Cepat 17+8 Tuntutan Rakyat:...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Partai Perindo merespons cepat 17+8 tuntutan rakyat yang berhimpun di koalisi masyarakat si
 Waktu: 03 September 2025
✅ Article #15 SCRAPPED! Title: Sering Ditawari Masuk Politik, Aurelie Moeremans: ...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA- Aktris Aurelie Moeremans rupanya pernah ditawari beberapa kali untuk terjun ke dunia polit
 Waktu: 02 September 2025
✅ Article #16 SCRAPPED! Title: Perkuat Struktur dan Strategi Menangkan Pemilu 202...
    100 KARAKTER PERTAMA DI CONTENT: SUMBA BARAT–Partai Perindomemantapkan langkah politik di Pulau Sumba, Nusa Tenggara Timur (NTT) deng
 Waktu: 28 Agustus 2025
✅ Article #17 SCRAPPED! Title: Pergeseran Kekuasaan di Madiun: Dinamika Politik P...
    100 KARAKTER PERTAMA DI CONTENT:  PERJANJIANGiyanti membawa perubahan besar bagi kehidupan di Pulau Jawa, terutama di bagian tengah s
 Waktu: 18 Agustus 2025
✅ Article #18 SCRAPPED! Title: Ketua DPD di HUT Ke-80 RI: Asta Cita Bukan Sekadar...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA– Ketua Dewan Perwakilan Daerah (DPD) RI, Sultan Baktiar Najamudin menekankan, bahwa Asta Ci
 Waktu: 17 Agustus 2025
✅ Article #19 SCRAPPED! Title: Puan Minta Izin Prabowo, DPR Bisa Menegur Politik ...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Ketua DPR RI, Puan Maharani, secara langsung meminta izin kepada Presiden Prabowo Subianto
 Waktu: 15 Agustus 2025
✅ Article #20 SCRAPPED! Title: Prabowo Curhat Perjalanan Politik: Ikut Pemilu 5 K...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA– Presiden Prabowo Subianto menceritakan perjalanan panjangnya sebelum akhirnya terpilih seb
 Waktu: 15 Agustus 2025

--- Scraping page: 3 ---
✅ Article #21 SCRAPPED! Title: Cita-Cita Jadi Dokter, Putri Zulhas Ungkap Alasan ...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Isu keterwakilan perempuan dalam ranahpolitikmasih menjadi pembahasan penting di Indonesia.
 Waktu: 14 Agustus 2025
✅ Article #22 SCRAPPED! Title: Putri Zulhas Ungkap Alasan Masuk Politik: Murni Pa...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Tak pernah membayangkan akan duduk di kursi parlemen,Putri Zulkifli Hasanatau biasa dijkena
 Waktu: 13 Agustus 2025
✅ Article #23 SCRAPPED! Title: Fero Walandouw Ngaku Bakal Fokus di Dunia Bisnis d...
    100 KARAKTER PERTAMA DI CONTENT:  Aktor kenamaan, Fero Walandouw membuat pernyataan mengejutkan bahwa dirinya bakal fokus di dunia bi
 Waktu: 12 Agustus 2025
✅ Article #24 SCRAPPED! Title: Kasus Korupsi CSR BI, KPK Telusuri Aliran Dana ke ...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA- Komisi Pemberantasan Korupsi (KPK) menetapkan dua anggota DPR RI sebagai tersangka, kasus
 Waktu: 08 Agustus 2025
✅ Article #25 SCRAPPED! Title: Beri Ruang Partisipasi Generasi Muda di Politik, P...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Partai Perindo menunjukkan dukungan penuh terhadap keterlibatan generasi muda dalam politik
 Waktu: 04 Agustus 2025
✅ Article #26 SCRAPPED! Title: Kongres VI PDIP Ditutup Hari Ini, Megawati Akan Sa...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA– Ketua Umum PDI Perjuangan, Megawati Soekarnoputri, tiba di Bali Nusa Dua Convention Center
 Waktu: 02 Agustus 2025
✅ Article #27 SCRAPPED! Title: Amnesti untuk Hasto, Ganjar: Menjadi Momentum Pene...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Ketua DPP PDI Perjuangan, Ganjar Pranowo, merespons langkah Presiden Prabowo Subianto yang
 Waktu: 01 Agustus 2025
✅ Article #28 SCRAPPED! Title: Mahfud MD: Amnesti Hasto dan Abolisi Tom Buktikan ...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Pakar hukum tata negara, Mahfud MD, mengomentari pemberian amnesti kepada Hasto Kristiyanto
 Waktu: 01 Agustus 2025
✅ Article #29 SCRAPPED! Title: Abolisi Tom Lembong dan Amnesti Hasto, Pengamat: P...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Dewan Perwakilan Rakyat (DPR) RI telah menyetujui usulan Presiden Prabowo Subianto untuk me
 Waktu: 01 Agustus 2025
✅ Article #30 SCRAPPED! Title: Relawan Jokowi: "Orang Besar" dalam Kisruh Ijazah ...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA- Polemik seputar keaslian ijazah Presiden ke-7 RI Joko Widodo memasuki babak baru, setelah
 Waktu: 30 Juli 2025

--- Scraping page: 4 ---
✅ Article #31 SCRAPPED! Title: LPS Cabut Izin 2 BPR, Ada Indikasi Terlibat Politi...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Lembaga Penjamin Simpanan (LPS) telah mencabut izin usaha dua Bank Perkreditan Rakyat (BPR)
 Waktu: 29 Juli 2025
✅ Article #32 SCRAPPED! Title: Hasto Divonis 3,5 Tahun Penjara, PDIP: Tahanan Pol...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Ketua DPP PDIP Djarot Saiful Hidayat, menyebut kasus yang menjerat Sekjen PDIPHasto Kristiy
 Waktu: 27 Juli 2025
✅ Article #33 SCRAPPED! Title: Vonis Hasto 3,5 Tahun Penjara, Hakim Tegaskan Tak ...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Majelis hakim Pengadilan Tipikor Jakarta menegaskan dalam memvonis Sekretaris Jenderal PDIP
 Waktu: 25 Juli 2025
✅ Article #34 SCRAPPED! Title: Hadiri Harlah ke-27 PKB, Sekjen Perindo: Sambung S...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA -Sekjen DPP Partai Perindo, Andi Yuslim Patawari (AYP) menghadiri kegiatan Hari Lahir ke-27P
 Waktu: 23 Juli 2025
✅ Article #35 SCRAPPED! Title: PN Jakpus Tegaskan Vonis Tom Lembong Murni Fakta H...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Pengadilan Negeri (PN) Jakarta Pusat menegaskan vonis yang dijatuhkan kepada Thomas Trikasi
 Waktu: 22 Juli 2025
✅ Article #36 SCRAPPED! Title: Rayuan Politik Ken Arok, Menarik Kaum Brahmana unt...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA- Konflik di wilayah Kerajaan Kediri saat dipimpin Raja Kertajaya dimanfaatkan betul oleh Ke
 Waktu: 16 Juli 2025
✅ Article #37 SCRAPPED! Title: Menakar Peluang Gerakan Rakyat Jadi Kendaraan Poli...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Ketua Umum (Ketum) DPP Gerakan Rakyat, Sahrin Hamid, mengaku masih jauh mengaitkan organisa
 Waktu: 13 Juli 2025
✅ Article #38 SCRAPPED! Title: Wall Street Lesu, Saham Tesla Anjlok 6 Persen Usai...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Bursa saham Amerika Serikat (AS), Wall Street, dibuka melemah pada awal perdagangan minggu
 Waktu: 07 Juli 2025
✅ Article #39 SCRAPPED! Title: Hasto Dituntut 7 Tahun Penjara, Kuasa Hukum: Ini B...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Tuntutan tujuh tahun penjara terhadap Sekretaris Jenderal (Sekjen) PDIP,Hasto Kristiyantome
 Waktu: 03 Juli 2025
✅ Article #40 SCRAPPED! Title: Komisi I DPR Nilai Serangan Israel ke Iran Bentuk ...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA- Anggota Komisi I DPR RI, Sukamta mengecam keras aksi militer Israel yang menyerang fasilit
 Waktu: 14 Juni 2025

--- Scraping page: 5 ---
✅ Article #41 SCRAPPED! Title: Soal Dana Penghijauan di Perkara Hasto, Ahli Bahas...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA-Ahli Bahasasekaligus Dosen Fakultas Ilmu Pengetahuan Budaya Universitas Indonesia (UI), Fran
 Waktu: 12 Juni 2025
✅ Article #42 SCRAPPED! Title: Rossa Isyaratkan Terjun ke Politik demi Perjuangka...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA-Rossamengungkapkan keinginannya untuk terjun ke dunia politik demi memperjuangkan kesejahter
 Waktu: 08 Juni 2025
✅ Article #43 SCRAPPED! Title: Isu Pemakzulan Gibran Disebut Tak Berdasar dan Hal...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Forum Purnawirawan Prajurit TNI yang menyurati Majelis Permusyawaratan Rakyat (MPR) soal us
 Waktu: 06 Juni 2025
✅ Article #44 SCRAPPED! Title: Dudung Tidak Maju Caketum karena Tidak Minat Polit...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Juru Bicara Partai Persatuan Pembangunan (PPP) Usman M Tokan mengaku telah mendengar kabar
 Waktu: 30 Mei 2025
✅ Article #45 SCRAPPED! Title: Dudung Abdurachman Putuskan Tak Maju Caketum PPP, ...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Penasihat Khusus Presiden Bidang Pertahanan Nasional Jenderal TNI (Purn)Dudung Abdurachmanm
 Waktu: 30 Mei 2025
✅ Article #46 SCRAPPED! Title: Terima Suap Rp593 Miliar, Mantan Penasihat Politik...
    100 KARAKTER PERTAMA DI CONTENT: BEIJING- Mantan penasihat politik seniorChina, Han Yong (68), dijatuhi hukuman mati dengan penangguh
 Waktu: 21 Mei 2025
✅ Article #47 SCRAPPED! Title: Kemendagri Usul Partai Politik Boleh Mendirikan Ba...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA- Kementerian Dalam Negeri (Kemendagri) mengusulkan, agar partai politik (parpol) bisa mendi
 Waktu: 21 Mei 2025
✅ Article #48 SCRAPPED! Title: Ketua KPU DKI Sebut Nilai Dana Bantuan Politik Rp7...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Ketua Komisi Pemilihan Umum (KPU) DKI Jakarta Wahyu Dinata menjelaskan nilai dana bantuan p
 Waktu: 20 Mei 2025
✅ Article #49 SCRAPPED! Title: DPW Perindo DKI Audiensi dengan KPUD Bahas Verifik...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Pengurus DPW Partai Perindo DKI Jakarta yang dipimpin Effendi Syahputra menyambangi Kantor
 Waktu: 20 Mei 2025
✅ Article #50 SCRAPPED! Title: DPR Nilai Pembuktian Praktik Politik Uang di Pilka...
    100 KARAKTER PERTAMA DI CONTENT:  JAKARTA- Anggota Komisi II DPR RI, Ahmad Irawan menyoroti putusan Mahkamah Konstitusi (MK) yang men
 Waktu: 19 Mei 2025

--- Scraping page: 6 ---
✅ Article #51 SCRAPPED! Title: MK Diskualifikasi Seluruh Paslon Pilkada Barito Ut...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Anggota Komisi II DPR RI Ahmad Irawan menilai, Putusan Mahkamah Konstitusi (MK) yang mendis
 Waktu: 16 Mei 2025
✅ Article #52 SCRAPPED! Title: Anies Baswedan Dirikan Ormas Aksi Bersama, Kendara...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Mantan Gubernur JakartaAnies Baswedanresmi meluncurkan organisasi 'Aksi Bersama' sekaligus
 Waktu: 15 Mei 2025
✅ Article #53 SCRAPPED! Title: Bebizie Raih Women's Inspiration Awards 2025, Insp...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA— Figur publik sekaligus anggota DPRD DKI Jakarta, Bebizie Sri Mulyati, kembali menegaskan ki
 Waktu: 02 Mei 2025
✅ Article #54 SCRAPPED! Title: Makan Siang Bareng Prabowo di Istana, Muzani: Tak ...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Ketua Majelis Permusyawaratan Rakyat (MPR) Ahmad Muzani mengatakan diundang makan siang ole
 Waktu: 29 April 2025
✅ Article #55 SCRAPPED! Title: Ketua DPP Partai Perindo Sri Gusni: Kerja Keras Ja...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Dunia politik saat ini masih menjadi arena yang penuh tantangan, terutama bagiperempuan. Ol
 Waktu: 28 April 2025
✅ Article #56 SCRAPPED! Title: Isu Ijazah Jokowi, Publik Diminta Jangan Serang Pe...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Isu tuduhan ijazah palsu Presiden ke-7 Joko Widodo (Jokowi) dinilai menjadi komoditas musim
 Waktu: 22 April 2025
✅ Article #57 SCRAPPED! Title: Konsultan Politik Sebut Partai Perindo Perlu Langk...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Konsultan politik nasional Eep Saefulloh Fatah menilai bahwa Partai Persatuan Indonesia (Pe
 Waktu: 22 April 2025
✅ Article #58 SCRAPPED! Title: Gelar Konsolidasi Hadapi Pemilu 2029, Partai Perin...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Partai Persatuan Indonesia (Perindo) menggelar konsolidasi di setiap provinsi secara lebih
 Waktu: 22 April 2025
✅ Article #59 SCRAPPED! Title: Kunjungan Serdik Sespimmen Polri ke Jokowi Dinilai...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Eks Komisioner Komisi Kepolisian Nasional (Kompolnas), Poengky Indarti menganggap, bahwa ku
 Waktu: 21 April 2025
✅ Article #60 SCRAPPED! Title: Konsultan Politik Eep Saepuloh Fatah Beberkan Apa ...
    100 KARAKTER PERTAMA DI CONTENT: BANDUNG- Konsultan politik nasional Eep Saepuloh Fatah memberikan masukan penting bagi Partai Perind
 Waktu: 20 April 2025

--- Scraping page: 7 ---
✅ Article #61 SCRAPPED! Title: Partai Perindo Jabar Panaskan Mesin Politik, Konso...
    100 KARAKTER PERTAMA DI CONTENT: BANDUNG- DPWPartai PerindoJabar memanaskan mesin politik untuk mengonsolidasi kekuatan dalam menghad
 Waktu: 19 April 2025
✅ Article #62 SCRAPPED! Title: Partai Perindo Panaskan Mesin Politik untuk 2029, ...
    100 KARAKTER PERTAMA DI CONTENT: KABUPATEN TANGERANG– Partai Perindo mulai memanaskan mesin politiknya menyambut pertarungan diPemilu
 Waktu: 17 April 2025
✅ Article #63 SCRAPPED! Title: Politik Jawa Barat Memanas! Malam Ini di Rakyat Be...
    100 KARAKTER PERTAMA DI CONTENT: Panggung politik Jawa Barat makin panas! Sorotan publik kian tajam tertuju pada dua nama besar Ridwa
 Waktu: 15 April 2025
✅ Article #64 SCRAPPED! Title: Idrus Marham soal Prabowo Ajak Dialog Tokoh Kritis...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA– Wakil Ketua Umum Partai Golkar, Idrus Marham, memuji langkahPresiden Prabowo Subiantoyang m
 Waktu: 13 April 2025
✅ Article #65 SCRAPPED! Title: Hadapi Tarif Trump, RI Harus Siapkan Langkah Polit...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Guru Besar Ilmu Ekonomi, Didik J Rachbini menilai tarif impor yang dikenakan Presiden AS Do
 Waktu: 10 April 2025
✅ Article #66 SCRAPPED! Title: Open House di Rumah Ketua MPR, Wamendagri Akui Ada...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Wakil Menteri Dalam Negeri (Wamendagri) Bima Arya mengakui ada pembahasan politik saat open
 Waktu: 02 April 2025
✅ Article #67 SCRAPPED! Title: Sekjen Gerindra Lebaran ke Rumah Megawati, Ngaku T...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Sekretaris Jenderal (Sekjen) Partai Gerindra Ahmad Muzani turut menyambangi kediaman Ketua
 Waktu: 31 Maret 2025
✅ Article #68 SCRAPPED! Title: Harta Kekayaan Atalia Praratya, Istri Ridwan Kamil...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Harta kekayaan Atalia Praratya, istri Ridwan Kamil yang terjun ke dunia politik menarik diu
 Waktu: 28 Maret 2025
✅ Article #69 SCRAPPED! Title: Jaksa KPK: Tak Ada Unsur Politik di Kasus Hasto Kr...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA -Jaksa Penuntut Umum (JPU) KPK menegaskan proses penanganan perkara Sekjen PDIP Hasto Kristi
 Waktu: 27 Maret 2025
✅ Article #70 SCRAPPED! Title: Prabowo Diminta Cermat Baca Situasi Politik dan Ta...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Pengesahan Rancangan Undang-Undang Tentara Nasional Indonesia (RUU TNI) menjadi UU oleh DPR
 Waktu: 24 Maret 2025

--- Scraping page: 8 ---
✅ Article #71 SCRAPPED! Title: Plt Sekjen Perindo AYP: Kontestasi Politik 2024 Pe...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Plt. Sekretaris Jenderal (Sekjen) DPP Partai Perindo, Andi Yuslim Patawari (AYP) menanggapi
 Waktu: 21 Maret 2025
✅ Article #72 SCRAPPED! Title: Sidang Eksepsi, Hasto Dikawal Pendukungnya Pakai R...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Pengadilan Tindak Pidana Korupsi (Tipikor) pada Pengadilan Negeri (PN) Jakarta Pusat kembal
 Waktu: 21 Maret 2025
✅ Article #73 SCRAPPED! Title: Pasar Modal, Krisis Politik Ekonomi dan Kebijakan...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Bagaimana membaca harga saham yang jatuh da terjungkal dalam beberapa hari ini? Pertanyaan
 Waktu: 19 Maret 2025
✅ Article #74 SCRAPPED! Title: Pengabdian, Hengky Kurniawan Tak Kapok Berkiprah d...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA-Hengky Kurniawanmenegaskan jika dirinya tak kapok berkiprah di politik meski gagal di Pilkad
 Waktu: 19 Maret 2025
✅ Article #75 SCRAPPED! Title: Vicky Pasetyo Temui Jokowi di Solo: Harus Punya Ag...
    100 KARAKTER PERTAMA DI CONTENT: SOLO–Vicky Prasetyomengunjungi kediaman mantan Presiden Joko Widodo (Jokowi) di Kelurahan Sumber, Ke
 Waktu: 14 Maret 2025
✅ Article #76 SCRAPPED! Title: Sidang Perdana, Hasto: Saya Adalah Tahanan Politik...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA -Sekretaris Jenderal PDIP,Hasto Kristiyantomenyebut dirinya merupakan tahanan politik. Hasto
 Waktu: 14 Maret 2025
✅ Article #77 SCRAPPED! Title: Hasto Tiba di Ruang Sidang, Disambut Pendukung Ber...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Pengadilan Tindak Pidana Korupsi (Tipikor) pada Pengadilan Negeri Jakarta Pusat menggelar s
 Waktu: 14 Maret 2025
✅ Article #78 SCRAPPED! Title: 8 Fakta Perjalanan Hidup Ifan Seventeen, Terjun ke...
    100 KARAKTER PERTAMA DI CONTENT: Perjalanan hidupIfan Seventeenmenarik untuk diulas. Pasalnya, pemilik nama lengkap Riefian Fajarsyah
 Waktu: 13 Maret 2025
✅ Article #79 SCRAPPED! Title: UU Parpol Digugat Persoalkan Masa Jabatan Ketum, T...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Dosen Hukum Tata Negara, Edward Thomas lamury Hadjon mengajukan gugatan terkait UUPartai Po
 Waktu: 10 Maret 2025
✅ Article #80 SCRAPPED! Title: Sarapan Gratis Kandas, Pramono Umbar Janji Politik...
    100 KARAKTER PERTAMA DI CONTENT: JAKARTA- Gubernur Jakarta,Pramono Anungmenyebutkan dirinya bersama Wakil Gubernur Rano Karno akan se
 Waktu: 08 Maret 2025

--- Scraping page: 9 ---
✅ Article #81 SCRAPPED! Title: Pilkada Serang, Pengamat: Andika Tumbang Wujud Pen...

In [ ]:
#save to csv
CSV_FILE = 'okezone_politik_articles.csv'
write_data_to_csv(CSV_FILE, CSV_HEADERS, okezone)
print(f"\n--- SCRAPING OKEZONE DONE! ({counter} article SCRAPPED!) ---")

✅ SUCCESS: Total 100 articles successfully saved to 'okezone_politik_articles.csv'

--- SCRAPING DONE! (100 article SCRAPPED!) ---

In [18]:
df = pd.read_csv('okezone_politik_articles.csv')
df.head()

,title,tanggal,waktu,content
0,"Pak Bas Lapor Progres IKN ke Istana, Persiapan...",03 Oktober 2025,16:52 WIB,JAKARTA- Kepala Otorita Ibu Kota Nusantara (OI...
1,"Fenomena Selebriti di Politik, Begini Pandanga...",01 Oktober 2025,20:55 WIB,"JAKARTA- Dalam episode terbaru Bisikan Gaib, R..."
2,SAS Institute: Program MBG Bukan Janji Politik...,01 Oktober 2025,20:20 WIB,JAKARTA– Badan Gizi Nasional (BGN) mencatat h...
3,"Husnan Bey: PPP Harus Kembali ke Khitah, Janga...",30 September 2025,18:38 WIB,JAKARTA- Muktamar X Partai Persatuan Pembangun...
4,Jokowi Sambut Baik Keputusan Prabowo Soal IKN ...,26 September 2025,16:56 WIB,SOLO– Keputusan Presiden Prabowo Subianto men...

# CNBC INDONESIA

In [15]:
# baca link berita
def get_article_cnbc(link):
    time_info_from_article = 'Time Not Found'
    content = ''
    try:
        res = requests.get(link, headers=headers)
        soup = BeautifulSoup(res.text, 'lxml')
        
        # ambil time dlu
        detail_head = soup.find('div', id='detailHead')
        if detail_head:
            # Mencari elemen waktu berdasarkan class yang spesifik
            time_tag = detail_head.find('div', class_='text-cm text-gray')
            if time_tag:
                time_info_from_article = time_tag.text.strip()
        
        #ambil konten
        div_content = soup.find('div', class_='detail-text') 
        if div_content:
            # Cari semua tag p di dalam div konten
            paragraphs = div_content.find_all('p') 
            content = ' '.join([p.get_text(strip=True) for p in paragraphs if p.get_text(strip=True)])
        
        return content, time_info_from_article
            
    except Exception as e:
        print(f"Error get article di: {link} | {e}")
    return content, time_info_from_article

In [16]:
# url list
urlcnbc = 'https://www.cnbcindonesia.com/search?query=politik'
cnbc_allpage = f'{urlcnbc}&fromdate=2015/09/01&todate=&kanal=news&tipe=artikel' 

rescnbc = requests.get(cnbc_allpage, headers=headers)
soupcnbc = BeautifulSoup(rescnbc.text, 'lxml')

In [17]:
pagenumbers = []
for a in soupcnbc.find_all('a'): #'a' bisa diganti, cek tag tag an di max page hsil search
  try:
    pagenumbers.append(int(a.get_text()))
  except:
    continue

lastpage = max(pagenumbers)
print(f"Halaman yg bisa di scraping: {lastpage}")

Halaman yg bisa di scraping: 834

In [18]:
# parsing waktuny cnbc
def parse_cnbc_time(time_info):
    time_info = time_info.replace(',', '').strip() # cleaning koma ama spasi

    # pindah ke DD Month YYYY HH:MM ( 04 October 2025 09:00)
    parts = time_info.split()
    if len(parts) >= 4:
        # Bagian tanggal ( '04 October 2025')
        tanggal = ' '.join(parts[:3]) 
        # Bagian waktu ('09:00')
        waktu = ' '.join(parts[3:]) 
        return tanggal, waktu
    
    # Fallback jika format gk dikenal
    tanggal = time_info
    waktu = 'N/A'
        
    return tanggal, waktu

In [ ]:
counter = 0
cnbc_batch = []   # buffer untuk batch tulis
# UJI: tulis tiap 10 artikel
BATCH_SIZE = 10
CSV_FILENAME = 'cnbc_politics_articles.csv'
# PRODUKSI: tulis tiap 1000 artikel
# BATCH_SIZE = 1000

for page in range(1, lastpage-831):
    url = f'{urlcnbc}&page={page}&fromdate=2015/09/01&todate=2025/09/31'
    try:
        res = requests.get(url, headers=headers, timeout=30)
        res.raise_for_status()
        soup = BeautifulSoup(res.text, 'lxml')
        articles = soup.find_all('article')

        if not articles:
            print(f"no articles found on page {page}")
            break

        for art in articles:
            try:
                a_tag = art.find('a')
                if not a_tag:
                    continue

                title = a_tag.find('h2').text.strip()
                link = a_tag['href']

                # ambil konten & waktu dari halaman detail
                content, time_info = get_article_cnbc(link)

                # parse waktu
                tanggal, waktu = parse_cnbc_time(time_info)

                # masukkan ke batch
                cnbc_batch.append([title, tanggal, waktu, content])

                print(f'✅ {counter} - {title} SCRAPPED!')
                print(f'    100 KARAKTER PERTAMA DI CONTENT: {content[:100]}\n    waktunya: {time_info}')
                counter += 1

                # ini klo dh sampe max batch, save dl ke CSV ama clear buffer
                if len(cnbc_batch) >= BATCH_SIZE:
                    append_rows_to_csv(CSV_FILENAME, CSV_HEADERS, cnbc_batch)
                    cnbc_batch.clear()

            except Exception as e:
                print(f"Error parsing artikel di hlman: {page} | {e}")
                continue

    except requests.exceptions.RequestException as e:
        print(f"Network error scraping page: {page} | {e}")
    except Exception as e:
        print(f"Error scraping (GENERAL) di hlman: {page} | {e}")
        continue

if cnbc_batch:
    append_rows_to_csv(CSV_FILENAME, CSV_HEADERS, cnbc_batch)
    cnbc_batch.clear()

✅ 0 - Mengapa Demo Gen Z Dunia Gunakan Bendera One Piece? Penjelasannya SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Bendera bajak laut 'Topi Jerami' dari anime populer "One Piece" telah menja
    waktunya: 06 October 2025 21:00
✅ 1 - Mengenal PM Terpilih Jepang Sanae Takaichi: Murid Abe ke "Wanita Besi" SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Panggung politik Jepang bersiap untuk menyambut era baru dengan terpilihnya
    waktunya: 06 October 2025 20:00
✅ 2 - Rupiah Perkasa Lawan Yen: Jalan-Jalan ke Jepang Bawa Rp 10 Juta Aman? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Nilai tukar rupiah mengalami penguatan yang cukup signifikan terhadap yen J
    waktunya: 06 October 2025 19:40
✅ 3 - Video: Di Balik Pertemuan Jokowi dan Prabowo di Kertanegara, Ada Apa? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Istana akhirnya menanggapi pertemuan antara Presiden Prabowo Subianto dan P
    waktunya: 06 October 2025 19:13
✅ 4 - Breaking News: Baru 27 Hari Menjabat, PM Prancis Mundur SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Perdana Menteri (PM) baruPrancis, Sebastien Lecornu, telah mengundurkan dir
    waktunya: 06 October 2025 16:55
✅ 5 - Analis Mulai Warning Pemerintah AS Shutdown, Ada Apa? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Penutupan (shutdown) pemerintah Amerika Serikat (AS) mungkin berlangsung se
    waktunya: 06 October 2025 15:25
✅ 6 - Goliat Vs Liliput: Cara Vietnam Menjadi Bangsa Pencipta SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Catatan:Artikel ini merupakan opini pribadi penulis dan tidak mencerminkan pandangan RedaksiCNBCIndo
    waktunya: 06 October 2025 13:41
✅ 7 - IHSG Galau, Saham Konglomerat RI Ramai-ramai Melesat SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Indeks Harga Saham Gabungan (IHSG) melemah tipis 0,06% atau terkoreksi 4,71
    waktunya: 06 October 2025 12:40
✅ 8 - 6 Minggu Beruntun Asing Kabur dari RI, Outflow Pecah Rekor SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Investor asing kembali mencatatkannet outflowatau keluar dari pasar keuanga
    waktunya: 06 October 2025 09:50
✅ 9 - IHSG Dibuka Naik 0,46%, Tembus Level 8.155,36 SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Indeks Harga Saham Gabungan (IHSG) dibuka naik 0,46% pagi ini, Senin (6/10/
    waktunya: 06 October 2025 09:05
💾 APPEND: 10 baris disimpan ke 'cnbc_politics_articles.csv'
✅ 10 - Rupiah Dibuka Stagnan, Dolar AS bertahan di Level Rp16.530/US$ SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Nilai tukar rupiah dibuka stagnan terhadap dolar Amerika Serikat (AS) pada
    waktunya: 06 October 2025 09:03
✅ 11 - Update Shutdown AS, Trump Siapkan PHK 750 Ribu PNS-Negosiasi Buntu SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Pemerintahan Amerika Serikat (AS) resmi mengalami shutdown sejak Rabu (1/10
    waktunya: 06 October 2025 08:50
✅ 12 - Bursa Asia Mayoritas Menguat, Jepang Jadi Sorotan SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Bursa Asia secara mayoritas bergerak naik pada awal pekan ini, Senin (6/10/
    waktunya: 06 October 2025 08:30
✅ 13 - Sejarah Dunia! Harga Emas Resmi Memasuki Level US$ 3.900 SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CBC Indonesia- Harga emas dan perak berpacu menciptakan rekor tertinggi. Harga logam mulia
    waktunya: 06 October 2025 06:41
✅ 14 - Influencer dan Aktivisme Politik SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Catatan:Artikel ini merupakan opini pribadi penulis dan tidak mencerminkan pandangan RedaksiCNBCIndo
    waktunya: 06 October 2025 06:25
✅ 15 - Badai Data di Depan Mata & Shutdown AS: RI Hadapi Pekan Menegangkan SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Pasar keuangan Tanah Air berhasil mencatatkan performa yang cukup kompak pa
    waktunya: 06 October 2025 06:15
✅ 16 - Elegi Hamas, Gaza Plan, dan "Kematian" Solusi Dua Negara SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Catatan:Artikel ini merupakan opini pribadi penulis dan tidak mencerminkan pandangan RedaksiCNBCIndo
    waktunya: 05 October 2025 18:24
✅ 17 - Habibie Sukses Turunkan Dolar dari Rp16.000 ke Rp6.550, Apa Rahasianya SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Belum lama ini, terjadi kekeliruan teknis pada Google yang menarik perhatia
    waktunya: 05 October 2025 18:15
✅ 18 - Sejarah Militer Dunia, Pasukan yang Membuat Dunia Berubah SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Sejarah militer dunia menyimpan banyak catatan tentang pasukan dan pemimpin
    waktunya: 05 October 2025 14:15
✅ 19 - F-35 Hingga Rafale, Inilah Daftar Senjata Paling Laku di Dunia SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Industri pertahanan global masih menunjukkan pola yang sama, sebagian besar
    waktunya: 05 October 2025 12:00
💾 APPEND: 10 baris disimpan ke 'cnbc_politics_articles.csv'
✅ 20 - 30 Negara yang Memilih Hidup Tanpa Militer SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Di tengah meningkatnya anggaran pertahanan dunia dan perlombaan memperkuat
    waktunya: 05 October 2025 11:00
✅ 21 - Harga Perak Tembus US$48, Dekati Rekor Tertinggi dalam 11 Tahun SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Harga perak dunia melesat tajam sepanjang pekan ini, menembus levelUS$48 pe
    waktunya: 05 October 2025 10:00
✅ 22 - Pemimpin Dunia-Jihad Islam Bersuara Respons Usulan Damai Trump di Gaza SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Presiden Amerika Serikat (AS) Donald Trump kembali menjadi sorotan usai men
    waktunya: 04 October 2025 21:30
✅ 23 - Sama-Sama Berisiko, Kenali Perbedaan Saham dan Obligasi-Pilih Mana? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Sejauh ini kita mengenal dua instrumen investasi yakni saham dan obligasi.
    waktunya: 04 October 2025 20:30

In [ ]:
print(f"\n🎉 DONNN: total artikel CNBC yang dah ke scraping: {counter}")

🎉 SELESAI: total artikel ter-scrape: 24

In [27]:
test = pd.read_csv('cnbc_politics_articles.csv')
test.head()

,title,tanggal,waktu,content
0,Mengapa Demo Gen Z Dunia Gunakan Bendera One P...,06 October 2025,21:00,"Jakarta, CNBC Indonesia -Bendera bajak laut 'T..."
1,Mengenal PM Terpilih Jepang Sanae Takaichi: Mu...,06 October 2025,20:00,"Jakarta, CNBC Indonesia -Panggung politik Jepa..."
2,Rupiah Perkasa Lawan Yen: Jalan-Jalan ke Jepan...,06 October 2025,19:40,"Jakarta, CNBC Indonesia- Nilai tukar rupiah me..."
3,Video: Di Balik Pertemuan Jokowi dan Prabowo d...,06 October 2025,19:13,"Jakarta, CNBC Indonesia- Istana akhirnya menan..."
4,"Breaking News: Baru 27 Hari Menjabat, PM Pranc...",06 October 2025,16:55,"Jakarta, CNBC Indonesia- Perdana Menteri (PM) ..."

# CNBC OLD CODE

In [7]:
counter = 0
cnbc = []

# main function to scrap
for page in range(1, lastpage+1):
  url = f'{urlcnbc}&page={page}&fromdate=2015/09/01&todate=2025/09/31' #test, dari 25 des 2024 smpe 1 jan 2025
  try:
    res = requests.get(url, headers=headers)
    soup = BeautifulSoup(res.text, 'lxml')
    articles = soup.find_all('article') #sesuaiin ke website 


    if not articles:
      print(f"no articles found on page {page}")
      break

    for art in articles:
      try:

        a_tag = art.find('a') #sesuaiin ke website (di cnbc ini ngebungkus berita, kek header gt)
        if not a_tag:
          continue

        title = a_tag.find('h2').text.strip() #sesuaiin ke website (di cnbc ini tag tag an buat judul)
        link = a_tag['href'] #sesuaiin ke website (di cnbc ini buat tembak site beritanya)
        #ambil konten ama tanggal
        content,time_info = get_article_cnbc(link)
        
        #ubah format tanggal
        tanggal, waktu = parse_cnbc_time(time_info)


        # add to cnbc
        cnbc.append([title, tanggal, waktu, content])
        
        print(f'✅ {counter} - {title} SCRAPPED!')
        print(f'    100 KARAKTER PERTAMA DI CONTENT: {content[:100]}\n waktunya: {time_info}')
        counter += 1
        # temp += 1
        # time.sleep(1)
        # if temp == 0 :
        #   time.sleep(59)
        #   temp = -100
        # if counter % 100 == 0: #setiap 100 article simpen
      
      except Exception as e:
        print(f"Error parsing artikel di hlman: {page} | {e}")
        continue
  except requests.exceptions.RequestException as e:
    print(f"Network error scraping page: {page} | {e}")
  except Exception as e:
    print(f"Error scraping (GENERAL) di hlman: {page} | {e}")
    continue

✅ 0 - Elegi Hamas, Gaza Plan, dan "Kematian" Solusi Dua Negara SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Catatan:Artikel ini merupakan opini pribadi penulis dan tidak mencerminkan pandangan RedaksiCNBCIndo
 waktunya: 05 October 2025 18:24
✅ 1 - Habibie Sukses Turunkan Dolar dari Rp16.000 ke Rp6.550, Apa Rahasianya SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Belum lama ini, terjadi kekeliruan teknis pada Google yang menarik perhatia
 waktunya: 05 October 2025 18:15
✅ 2 - Sejarah Militer Dunia, Pasukan yang Membuat Dunia Berubah SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Sejarah militer dunia menyimpan banyak catatan tentang pasukan dan pemimpin
 waktunya: 05 October 2025 14:15
✅ 3 - F-35 Hingga Rafale, Inilah Daftar Senjata Paling Laku di Dunia SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Industri pertahanan global masih menunjukkan pola yang sama, sebagian besar
 waktunya: 05 October 2025 12:00
✅ 4 - 30 Negara yang Memilih Hidup Tanpa Militer SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Di tengah meningkatnya anggaran pertahanan dunia dan perlombaan memperkuat
 waktunya: 05 October 2025 11:00
✅ 5 - Harga Perak Tembus US$48, Dekati Rekor Tertinggi dalam 11 Tahun SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Harga perak dunia melesat tajam sepanjang pekan ini, menembus levelUS$48 pe
 waktunya: 05 October 2025 10:00
✅ 6 - Pemimpin Dunia-Jihad Islam Bersuara Respons Usulan Damai Trump di Gaza SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Presiden Amerika Serikat (AS) Donald Trump kembali menjadi sorotan usai men
 waktunya: 04 October 2025 21:30
✅ 7 - Sama-Sama Berisiko, Kenali Perbedaan Saham dan Obligasi-Pilih Mana? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Sejauh ini kita mengenal dua instrumen investasi yakni saham dan obligasi.
 waktunya: 04 October 2025 20:30
✅ 8 - Breaking News! Sanae Takaichi Sah Terpilih Jadi Perdana Menteri Jepang SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Sanae Takaichi baru saja terpilih menjadi pemimpin wanita pertama Jepang. D
 waktunya: 04 October 2025 20:03
✅ 9 - Peramal India Datangi Ibu Tien, Awalnya Ditolak-Ramalannya Jadi Nyata SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Ramalan selalu jadi bagian menarik dalam perjalanan kehidupan manusia. Ada
 waktunya: 04 October 2025 18:45
✅ 10 - Ancaman Nyata Intai IKN, BRIN Temukan Krisis-Bisa Ganggu Kehidupan SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Badan Riset dan Inovasi Nasional (BRIN) mengungkap temuan mencemaskan soal
 waktunya: 04 October 2025 18:15
✅ 11 - Mendadak Jokowi-Prabowo Bertemu Rahasia, Bicara 4 Mata 2 Jam SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Presiden ke-7 RI Joko Widodo (Jokowi) diketahui bertemu dengan Presiden ke-
 waktunya: 04 October 2025 17:22
✅ 12 - Iran Gantung Mati 6 Anggota "Kelompok Teroris" yang Terkait Zionis SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Pemerintah Iran mengeksekusi enam orang yang disebut sebagai anggota kelomp
 waktunya: 04 October 2025 15:45
✅ 13 - Sanae Takaichi Bakal Jadi PM Perempuan Pertama Jepang, "Iron Lady 2.0" SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia-Jepang bersiap menyambut babak baru dalam sejarah politiknya dengan terpilih
 waktunya: 04 October 2025 14:00
✅ 14 - Warga RI Korupsi Uang Rp1,3 T & Kabur ke China, Kini Dikejar Interpol SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Sejumlah warga Indonesia pernah masuk daftar red notice Interpol. Sebagian
 waktunya: 04 October 2025 12:00
✅ 15 - Rupiah Tendang Dolar AS, Pimpin Asia Bareng Yen dan Peso! SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Rupiah berhasil menutup perdagangan pekan ini dengan kinerja ciamik dalam m
 waktunya: 04 October 2025 10:15
✅ 16 - Chaos Madagaskar Berlanjut, Gen Z Menggila-Presiden Ogah Mundur SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Gelombang protes besar-besaran yang dipimpin anak muda di Madagaskar terus
 waktunya: 04 October 2025 09:30
✅ 17 - Hamas Setuju Usulan Damai AS, Trump Perintahkan Israel Setop Bom Gaza SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Presiden Amerika Serikat (AS) Donald Trump menanggapi positif respons Hamas
 waktunya: 04 October 2025 09:00
✅ 18 - Rekor Baru! Emas Naik Gila-gilaan, Harga Tertinggi Sepanjang Masa SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Harga emas dunia kembali menguat hingga mencatatkan rekor penutupan terting
 waktunya: 04 October 2025 07:00
✅ 19 - Trump Unggah Video Musik AI, Sindir Demokrat soal Anggaran SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Presiden Amerika Serikat (AS) Donald Trump kembali bikin heboh. Ia membagik
 waktunya: 03 October 2025 21:30
✅ 20 - Jepang Berpeluang Punya Perdana Menteri Perempuan Pertama SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Jepang berpeluang memiliki perdana menteri (PM) perempuan pertama. Sabtu es
 waktunya: 03 October 2025 17:00
✅ 21 - Pak Bas Merapat ke Istana Bahas IKN, Sampaikan Rencana 2026-2028 SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Kepala Otorita Ibu Kota Nusantara Basuki Hadimuljono menyambangi Kementeria
 waktunya: 03 October 2025 16:58
✅ 22 - Emas Menggila! Siapa Tertawa Paling Keras di Balik Kenaikan Harga Ini? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Harga emas dunia kembali menunjukkan kekuatannya dengan menembus level psik
 waktunya: 03 October 2025 14:35
✅ 23 - Indonesia di Persimpangan Sejarah SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Catatan:Artikel ini merupakan opini pribadi penulis dan tidak mencerminkan pandangan RedaksiCNBCIndo
 waktunya: 03 October 2025 12:45
✅ 24 - Chaos! Demo "GenZ 212" Guncang Maroko, Makan Korban Jiwa-Bank Dibakar SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Kerusakan usai protes anti-pemerintah yang dipimpin pemuda di Sale, Maroko, Kamis (2/10/2025). (REUT
 waktunya: 03 October 2025 10:40
✅ 25 - 7 Update AS Shutdown: 7 Juta Warga Terancam Kelaparan-Jalan Tol Resesi SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia - Pemerintah Amerika Serikat (AS) secara resmi menghentikan sebagian besar o
 waktunya: 03 October 2025 08:05
✅ 26 - Polisi Tembak Mati Para Pendemo GenZ 212, 3 Orang Tewas SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Setidaknya tiga orang tewas di Maroko dalam protes pemuda terhadap dugaan k
 waktunya: 03 October 2025 06:10
✅ 27 - IHSG & Rupiah Hadapi "Bear Killer" Oktober di Tengah Gejolak Dunia SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Pasar keuangan Tanah Air akhirnya kompak melesat bersama. Baik Indeks Harga
 waktunya: 03 October 2025 05:54
✅ 28 - Startup Sudah Tak Laku, Ramai-ramai Beralih Jualan Senjata Pembunuh SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Sejumlah pendiri startup di Silicon Valley beralih dari 'jualan' produk kon
 waktunya: 02 October 2025 21:00
✅ 29 - Video: Pengamat Politik Ramal Shutdown di AS Akan Berakhir SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia-Pengamat politik menilai penyelesaian baru akan terjadi jika salah satu piha
 waktunya: 02 October 2025 20:30
✅ 30 - Video: Trump Bekukan Dana USD 26 Miliar, Shutdown Kian Politis SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia-Pemerintah Amerika Serikat saat ini mengalami shutdown untuk ke-15 kalinya s
 waktunya: 02 October 2025 20:00
✅ 31 - Silmy Karim Umumkan Seleksi Dirjen Imigrasi, Ini Hasilnya! SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Ketua Panitia Seleksi Terbuka Jabatan Pimpinan Tinggi (JPT) Madya Kementeri
 waktunya: 02 October 2025 19:31
✅ 32 - Kementerian BUMN Jadi BP BUMN, Ini Daftar Lengkap K/L Kabinet Prabowo SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta,CNBCIndonesia- Kementerian dan Lembaga di Era Presiden Prabowo Subianto kembali mengalami pe
 waktunya: 02 October 2025 17:50
✅ 33 - Sejarah Shutdown Amerika, dari Ford - Trump: Mana Paling Lama? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Pemerintah Amerika Serikat (AS) resmi mengalami shutdown pada Rabu (1/10/20
 waktunya: 02 October 2025 17:30
✅ 34 - Bongkar! Ini Jeroan Anggaran AS yang Bikin Negara Shutdown SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Pemerintah Amerika Serikat (AS) resmi lumpuh sejak Rabu (1/10/2025) pada pu
 waktunya: 02 October 2025 16:50
✅ 35 - IHSG Kembali ke Zona Hijau, Ditutup naik 0,34% Hari Ini SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Indeks Harga Saham Gabungan (IHSG) kembali ke zona positif setelah dua hari
 waktunya: 02 October 2025 16:39
✅ 36 - Rupiah Menguat 5 Hari Beruntun, Dolar AS Turun ke Rp 16.580 SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Mata uang rupiah kembali menunjukkan penguatan terhadap dolar Amerika Serik
 waktunya: 02 October 2025 15:09
✅ 37 - Bikin Kaget! 5 Komoditas Ini Harganya Melonjak Lebih Dahsyat dari Emas SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia-Harga emas dunia kembali jadi sorotan setelah menembus rekor baru, nyaris me
 waktunya: 02 October 2025 13:01
✅ 38 - Menguatkan Transformasi Zakat Demi Mengangkat Martabat Umat SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Catatan:Artikel ini merupakan opini pribadi penulis dan tidak mencerminkan pandangan RedaksiCNBCIndo
 waktunya: 02 October 2025 12:25
✅ 39 - IHSG Sesi I Naik 0,4%, Bisa Bertahan Sampai Sore? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Indeks Harga Saham Gabungan (IHSG) naik 0,36% atau 28,77 poin ke level 8.07
 waktunya: 02 October 2025 12:21
✅ 40 - Purbaya Siapkan Skema Campuran APBN, KPBU, dan FDI untuk Biayai IKN SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Pemerintah menegaskan kembali strategi pembiayaan pembangunan Ibu Kota Nusa
 waktunya: 02 October 2025 11:11
✅ 41 - Video: Demokrat Vs Republik Saling Tuding, Pemerintah AS Shutdown SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Pemerintah Amerika Serikat resmi mengalami shutdown setelah Senat gagal mel
 waktunya: 02 October 2025 10:54
✅ 42 - AI Bikin Harga Listrik Naik 4 Kali Lipat, Warga Ngamuk Susah Bayar SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Amerika Serikat kini menghadapi krisis baru, yakni lonjakan harga listrik y
 waktunya: 02 October 2025 10:40
✅ 43 - Banyak Sentimen Positif, IHSG Dibuka Menguat 0,33% SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Indeks Harga Saham Gabungan (IHSG) dibuka naik 0,33% atau menguat 26,60 poi
 waktunya: 02 October 2025 09:06
✅ 44 - Shutdown Amerika Makan Korban: Penerbangan-Keselamatan Penumpang SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia-Shutdownyang terjadi di pemerintahan Amerika Serikat (AS) membuat kekhawatir
 waktunya: 02 October 2025 08:38
✅ 45 - Usai Purbaya Effect, RI Menguji Kesaktian Oktober Sebagai Bear Killer SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Dunia pasar modal memasuki Oktober dengan sebuah mitos populer. Bulan kesep
 waktunya: 02 October 2025 08:30
✅ 46 - 9 Update Pemerintah AS Shutdown: PHK Massal Depan Mata-Trump Jatuh SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Pemerintah federal Amerika Serikat (AS) secara resmi menghentikan sebagian
 waktunya: 02 October 2025 07:34
✅ 47 - Pemilik Emas, Bersiaplah: Pesta Baru Dimulai, US$4000 Bukan Lagi Batas SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Harga emas melesat nyaris mendekati US$3.900 per troy ons. Harga emas menca
 waktunya: 02 October 2025 07:20
✅ 48 - Hilirisasi Pertanian Kunci Kesejahteraan Petani SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Catatan:Artikel ini merupakan opini pribadi penulis dan tidak mencerminkan pandangan RedaksiCNBCIndo
 waktunya: 02 October 2025 06:15
✅ 49 - Chaos! Potret Gen Z Madagaskar Ngamuk Tuntut Presiden Mundur SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Seorang pengunjuk rasa menendang tabung gas air mata yang dilemparkan oleh petugas polisi anti huru-
 waktunya: 01 October 2025 21:50
✅ 50 - Shutdown Pemerintahan AS, Ini yang Bakal Terjadi Selanjutnya SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Kebuntuan politik di Kongres Amerika Serikat berujung pada penghentian seme
 waktunya: 01 October 2025 21:40
✅ 51 - Shutdown Pemerintah AS: Pasar Bergejolak, RI Ketiban Durian Runtuh? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Pemerintah AmerikaSerikat (AS) resmi mengalamigovernment shutdownpada Rabu
 waktunya: 01 October 2025 20:10
✅ 52 - Paradoks Transisi Energi Indonesia SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Catatan:Artikel ini merupakan opini pribadi penulis dan tidak mencerminkan pandangan RedaksiCNBCIndo
 waktunya: 01 October 2025 18:10
✅ 53 - Kepada Pemilik Bitcoin: Persiapkan Strategi Ini Selama Oktober SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Bitcoin tengah mengalami penguatan sejak hancurnya FTX pada 2022. FTX merup
 waktunya: 01 October 2025 17:50
✅ 54 - Mahfud MD Cerita Cucunya Keracunan MBG, Dirawat 4 Hari di Rumah Sakit SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Yogyakarta, CNBC Indonesia- Menteri Koordinator Bidang Politik, Hukum, dan Keamanan periode 2019-202
 waktunya: 01 October 2025 16:18
✅ 55 - Tok! Mantan Presiden Divonis Hukuman Mati Usai Terlibat Perang Saudara SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Pengadilan militer tertinggi di Republik Demokratik Kongo pada Selasa (30/9
 waktunya: 01 October 2025 15:05
✅ 56 - Cerita Uya Kuya Kehilangan Mahar Pernikahan usai Rumahnya Dijarah SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Setelah hampir sebulan, presenter sekaligus anggota DPR RI non-aktif Uya Ku
 waktunya: 01 October 2025 13:35
✅ 57 - Chaos Demo Madagaskar Menggila, Pemerintah Bubar-Gen Z Belum Puas SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Gelombang protes besar-besaran yang digerakkan oleh anak muda atau gen Z di
 waktunya: 01 October 2025 13:30
✅ 58 - Dua Warga RI Minta MK Hapus Hak Pensiun Anggota DPR SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Dua orang warga Indonesia mengajukan uji materil terhadap Undang-Undang Nom
 waktunya: 01 October 2025 12:52
✅ 59 - Pengusaha RI Pede Tapi Was-Was, Tandanya Terlihat di Pabrik Rokok-Obat SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Indeks Kepercayaan Industri (IKI) bulan September 2025 dilaporkan mengalami
 waktunya: 01 October 2025 12:40
✅ 60 - Koruptor Terbesar RI Kabur Usai Suap Sipir Penjara, Diburu 179 Negara SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Sejumlah warga Indonesia pernah masuk daftarred noticeInterpol. Sebagian be
 waktunya: 01 October 2025 11:05
✅ 61 - Ternyata Ini Alasan Soeharto Tetapkan 1 Oktober Jadi Hari Pancasila SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Setiap tanggal 1 Oktober, Indonesia memperingati Hari Kesaktian Pancasila.
 waktunya: 01 October 2025 10:55
✅ 62 - Cucu Mahfud MD di Jogja Keracunan MBG SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Yogyakarta, CNBC Indonesia- Menteri Koordinator Bidang Politik, Hukum, dan Keamanan periode 2019-202
 waktunya: 01 October 2025 10:11
✅ 63 - Awal Oktober Suram: Asia Kebakaran Lagi, Rupiah, Won - Ringgit Ambruk SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Pada awal Perdagangan Oktober, Rabu (1/10/2025), mayoritas mata uang Asia t
 waktunya: 01 October 2025 09:53
✅ 64 - Shutdown AS di Depan Mata, Trump Tiba-Tiba Beri Warning Ngeri Ini SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Amerika Serikat (AS) masih berada dalam ancaman penghentian kegiatan pemeri
 waktunya: 01 October 2025 07:45
✅ 65 - Badai Sentimen Mengintai RI: Inflasi, Ekonomi China & Shutdown Amerika SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Pasar keuangan Tanah Air tidak berjalan seirama. Indeks Harga Saham Gabunga
 waktunya: 01 October 2025 06:20
✅ 66 - Video: Baliho Prabowo di Israel, Propaganda Politik Netanyahu? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Foto-foto baliho Presiden RI Prabowo Subianto berdampingan dengan sejumlah
 waktunya: 30 September 2025 18:25
✅ 67 - Chaos! Demo Gen Z Memanas, Presiden Minta Maaf & Bubarkan Pemerintahan SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Demonstrasi besar-besaran yang melanda kota-kota di Madagaskar memaksa Pres
 waktunya: 30 September 2025 16:00
✅ 68 - Warga RI Makin Gampang Cari Kerja di China, Begini Syaratnya SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Kebijakan baru Amerika Serikat (AS) yang menetapkan biaya visa kerja H-1B h
 waktunya: 30 September 2025 15:45
✅ 69 - Rupiah Ditutup Menguat, Dolar AS Turun ke Rp16.660 SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia— Nilai tukar rupiah ditutup menguat terhadap dolar Amerika Serikat (AS) pada
 waktunya: 30 September 2025 15:09
✅ 70 - Ini Reaksi Hamas soal Deal Trump-Netanyahu, Perang Gaza Kelar? SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Seorang pejabat seniorHamasmengatakan bahwa kelompok itu akan "merespons" k
 waktunya: 30 September 2025 13:05
✅ 71 - Shutdown Jadi Hantu Abadi Ekonomi AS: Puluhan Presiden Jadi Korban SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Pemerintah Amerika Serikat (AS) saat ini sedang menghadapi ancaman governme
 waktunya: 30 September 2025 12:35
✅ 72 - Ekosistem Baterai EV Ubah Paradigma Ekonomi Indonesia SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Catatan:Artikel ini merupakan opini pribadi penulis dan tidak mencerminkan pandangan RedaksiCNBCIndo
 waktunya: 30 September 2025 12:15
✅ 73 - 6 Alasan Kenapa Harga Emas Bisa Meledak ke Langit SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Harga emas terus mencetak rekor-rekor baru. Kini berhasil menembus level ps
 waktunya: 30 September 2025 11:50
✅ 74 - Pasar Kelebihan Pasokan, Harga Minyak Dunia Anjlok SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia -Harga minyak dunia kembali tergelincir pada perdagangan Selasa (30/9/2025)
 waktunya: 30 September 2025 10:45
✅ 75 - Tetangga RI 'Macan Asia' Terancam Resesi, Bakal Kena di 2040 SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Korea Selatan (Korsel) mencatat peningkatan angka kelahiran di 2024. Ini me
 waktunya: 30 September 2025 09:58
✅ 76 - Rupiah Kembali Menguat, Dolar AS Dibuka Turun ke Rp16.650 SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Nilai tukar rupiah dibuka menguat terhadap dolar Amerika Serikat (AS) seiri
 waktunya: 30 September 2025 09:04
✅ 77 - Lanjutkan Reli, IHSG Dibuka Menguat Tipis 0,18% ke 8.137 SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Indeks Harga Saham Gabungan (IHSG) dibuka menguat 0,18% atau naik 14,39 poi
 waktunya: 30 September 2025 09:03
✅ 78 - Kirim 7 Desakan Darurat Ekonomi, Ini Profil Aliansi Ekonom Indonesia SCRAPPED!
    100 KARAKTER PERTAMA DI CONTENT: Jakarta, CNBC Indonesia- Aliansi Ekonom Indonesia bertandang ke kantor Menteri Koordinator Bidang Pe
 waktunya: 30 September 2025 07:55
✅ 79 - Akhir Perang Gaza di Depan Mata, Trump Sepakati Ini Dengan Netanyahu SCRAPPED!

In [8]:
#save to csv
CSV_FILE = 'cnbc_politik_articles.csv'
write_data_to_csv(CSV_FILE, CSV_HEADERS, cnbc)
print(f"\n--- SCRAPING CNBC DONE! ({counter} article SCRAPPED!) ---")

✅ SUCCESS: Total 10000 articles successfully saved to 'cnbc_politik_articles.csv'

--- SCRAPING CNBC DONE! (10000 article SCRAPPED!) ---

In [10]:
df = pd.read_csv('cnbc_politik_articles_2.csv')
df.head()

,title,tanggal,waktu,content
0,"Elegi Hamas, Gaza Plan, dan ""Kematian"" Solusi ...",05 October 2025,18:24,Catatan:Artikel ini merupakan opini pribadi pe...
1,Habibie Sukses Turunkan Dolar dari Rp16.000 ke...,05 October 2025,18:15,"Jakarta, CNBC Indonesia -Belum lama ini, terja..."
2,"Sejarah Militer Dunia, Pasukan yang Membuat Du...",05 October 2025,14:15,"Jakarta, CNBC Indonesia— Sejarah militer dunia..."
3,"F-35 Hingga Rafale, Inilah Daftar Senjata Pali...",05 October 2025,12:00,"Jakarta, CNBC Indonesia— Industri pertahanan g..."
4,30 Negara yang Memilih Hidup Tanpa Militer,05 October 2025,11:00,"Jakarta, CNBC Indonesia— Di tengah meningkatny..."